# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Perform base checks
        run: ./gradlew app:assembleDebug
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Execute unit tests
        run: ./gradlew form:testDebugUnitTest
      - name: Upload unit tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: unit_tests
          path: ./form/build/outputs/unit_test_code_coverage/debugUnitTest/
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [32]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          ram-size: 4096M
          disable-animations: true
          profile: Nexus 6
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated
          script: ./gradlew connectedCheck
      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: emulator_tests_${{ matrix.api-level }}
          path: ./form/build/outputs/code_coverage/debugAndroidTest/connected
  CODE_COVERAGE:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: [ANDROID_UNIT_TESTS, ANDROID_EMULATOR_TESTS]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Download unit tests artifact
        uses: actions/download-artifact@v1
        with:
          name: unit_tests
          path: ./form/build/jacoco/
      - name: Download emulator tests artifact
        uses: actions/download-artifact@v1
        with:
          name: emulator_tests_32
          path: ./form/build/outputs/code_coverage/debugAndroidTest/connected
      - name: Create coverage report
        run: ./gradlew form:jacocoTestReport
      - name: Upload coverage report (GitHub)
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: ./form/build/reports/jacoco/jacocoTestReport
      - name: Upload coverage report (Codecov)
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_KEY }}
          file: ./form/build/reports/jacoco/jacocoTestReport/*
          fail_ci_if_error: true
