name: Publish

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  MAVEN_UPLOAD:
    name: Maven Upload
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SONATYPE_USER: ${{ secrets.OSSRH_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Perform maven upload
        run: ./gradlew publishToSonatype --stacktrace